package org.omg.PortableServer;


/**
* org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u91/6644/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Friday, April 1, 2016 12:59:25 AM PDT
*/

public interface SERVANT_RETENTION_POLICY_ID
{

  /**
	 * The value representing SERVANT_RETENTION_POLICY_ID.
	 */
  public static final int value = (int)(21L);
}
